### ISSUE TITLE
issue-01-No such file or directory

### ISSUE THREAD

**Issue by changshengee** [IoTcat/kms#2]
$ cat %temp%\kms.log
cat: %temp%kms.log: No such file or directory

激活日志提示  No such file or directory

**Comment by yimianxyz** [comment]
`kms.log`位于系统临时文件夹中，系统重启时将被自动删除。如需查看`kms.log`内容，请在执行激活脚本后立即查看。   

------------
P.S. `kms.log`并非严格意义上的日志，只是脚本捕获的关键系统输出。例如`成功地安装了产品密钥 W269N-WFGWX-YVC9B-4J6C9-T83GX。`。其中的信息并不重要，这也是我将它设计在临时文件夹的原因。
