### ISSUE TITLE
只能激活6个月的么

### ISSUE THREAD

**Issue by Youwenrui** [IoTcat/kms#3]
只能激活6个月的么

**Comment by yimianxyz** [comment]
对于批量激活，您的系统必须通过至少每180 天连接一次KMS 服务器来续订激活。 默认情况下，系统每7 天自动进行一次激活续订尝试。 在续订客户端激活之后，激活有效间隔重新开始。 综上所述，只要您的电脑不超过180 天以上无法连接互联网，就无需进行任何操作，系统会自行续期保持激活状态。

对于永久激活（成功概率较低），您的系统无需联网即可永久使用。

**Comment by Youwenrui** [comment]
> 对于批量激活，您的系统必须通过至少每180 天连接一次KMS 服务器来续订激活。 默认情况下，系统每7 天自动进行一次激活续订尝试。 在续订客户端激活之后，激活有效间隔重新开始。 综上所述，只要您的电脑不超过180 天以上无法连接互联网，就无需进行任何操作，系统会自行续期保持激活状态。
> 
> 对于永久激活（成功概率较低），您的系统无需联网即可永久使用。

OK，谢谢
